server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.174.131:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.174.131
    port: 5672
    virtual-host: /xiaohuo
    username: xiaohuo
    password: 123456
    listener:
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: trace